revert VocaDb.ResXFileCodeGenerator
revert https://github.com/ufcpp/ValueChangedGenerator/pull/6 except for `LangVersion, `Nullable`, and NuGet.config

VocaDb.ResXFileCodeGenerator causes compile error:

CSC : warning CS8785: Generator 'SourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'ValueChangedGenerator.Resources.g.cs' of the added source file must be unique within a generator.
ValueChangedGeneratorAnalyzer.cs(17,96,17,105): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(17,122,17,131): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(17,156,17,165): error CS0246: The type or namespace name 'Resources' could not be found (are you missing a using directive or an assembly reference?)
ValueChangedGeneratorAnalyzer.cs(18,104,18,113): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(18,138,18,147): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(18,172,18,181): error CS0246: The type or namespace name 'Resources' could not be found (are you missing a using directive or an assembly reference?)
ValueChangedGeneratorAnalyzer.cs(19,102,19,111): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(19,134,19,143): error CS0103: The name 'Resources' does not exist in the current context
ValueChangedGeneratorAnalyzer.cs(19,168,19,177): error CS0246: The type or namespace name 'Resources' could not be found (are you missing a using directive or an assembly reference?)